# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# # Use a package of configuration called an orb.
# orbs:
#   # Declare a dependency on the welcome-orb
#   welcome: circleci/welcome-orb@0.4.1
# # Orchestrate or schedule a set of jobs
# workflows:
#   # Name the workflow "welcome"
#   welcome:
#     # Run the welcome/run job in its own container
#     jobs:
#       - welcome/run


# version: 2.1
# orbs:
#   packer: salaxander/packer@0.0.3
# jobs:
#   packer-aws-ami:
#     executor: packer/default
#     steps:
#       - checkout
#       - packer/build:
#           template: template/ami_ec2.json
#           args: '-var aws_access_key=${aws_access_key} -var aws_secret_key=${aws_secret_key} -var aws_region=us-east-1 -var ami_users=${ami_users}'
# workflows:
#   version: 2
#   packer:
#     jobs:
#       - packer-aws-ami

version: 2
jobs:
  packer-aws-ami:
    docker:
    - image: hashicorp/packer:1.5.1
    steps:
    - checkout
    - run:
        name: Run a packer build
        command: packer build -var aws_access_key=${aws_access_key} -var aws_secret_key=${aws_secret_key} -var aws_region=us-east-1 -var ami_users=${ami_users} template/ami_ec2.json
workflows:
  version: 2
  packer:
    jobs:
    - packer-aws-ami